### ISSUE TITLE
Initial project roadmap

### ISSUE THREAD

**Issue by danielrosehill** [danielrosehill/Impact-Weighted-Accounts-Demo-App#1]
**Preparatory steps**

- [ ] Add data release
- [ ] Add licensing notes and attribution of data sources
- [ ] Convert data source from .xlsx to JSON or other format
